services:
  postgres:
    image: postgres:16-alpine
    container_name: souk_tchad_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: souk_tchad
      POSTGRES_PASSWORD: souk_tchad_dev
      POSTGRES_DB: souk_tchad
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
